<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.mule.extensions</groupId>
		<artifactId>mule-modules-parent</artifactId>
		<version>1.8.3</version>
	</parent>
	<groupId>au.com.apiled.module.plugins</groupId>
	<artifactId>advanced-logger</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>mule-plugin</packaging>
	<name>Advanced Logger</name>

	<properties>
		<mule.version>4.6.3</mule.version>
		<skipVerifications>true</skipVerifications>
		<java.version>17</java.version>
		<versions.plugin.version>2.18.0</versions.plugin.version>
		<jacoco.plugin.version>0.8.11</jacoco.plugin.version>
		<maven.compiler.release>17</maven.compiler.release>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-site-plugin</artifactId>
				<configuration>
					<skip>true</skip>
					<skipDeploy>true</skipDeploy>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.mule.runtime.plugins</groupId>
				<artifactId>mule-plugin-maven-plugin</artifactId>
				<extensions>true</extensions>
			</plugin>
		</plugins>
		<pluginManagement>
			<plugins>
				<!-- Default to Java 17 level source and bytecode -->
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>3.13.0</version>
					<configuration>
						<release>${java.version}</release>
						<source>${java.version}</source>
						<target>${java.version}</target>
					</configuration>
				</plugin>

				<!-- Version Number Management for Maven configuration units -->
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>versions-maven-plugin</artifactId>
					<version>${versions.plugin.version}</version>
					<configuration>
						<!-- The Build process can only update to the latest
						build revision, 
							no major/minor version bumps (these have to be done manually) -->
						<allowMajorUpdates>false</allowMajorUpdates>
						<allowMinorUpdates>false</allowMinorUpdates>
						<allowIncrementalUpdates>true</allowIncrementalUpdates>

						<!-- Don't consider SNAPSHOT versions - we need
						repeatable builds with 
							unique version numbers -->
						<allowSnapshots>false</allowSnapshots>

						<!-- Only manage version numbers for configuration units
						in the CI 
							process -->
						<includes>
							<include>au.com.apiled:*</include>
						</includes>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.jacoco</groupId>
					<artifactId>jacoco-maven-plugin</artifactId>
					<version>${jacoco.plugin.version}</version>
					<executions>
						<execution>
							<id>default-prepare-agent</id>
							<goals>
								<goal>prepare-agent</goal>
							</goals>
						</execution>
						<execution>
							<id>default-report</id>
							<phase>prepare-package</phase>
							<goals>
								<goal>report</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-release-plugin</artifactId>
					<version>3.1.1</version>
					<configuration>
						<autoVersionSubmodules>true</autoVersionSubmodules>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>

	</build>
	<dependencies>
<!--		<dependency>
			<groupId>org.mule.runtime</groupId>
			<artifactId>mule-core</artifactId>
			<version>${mule.version}</version>
			<scope>provided</scope>
		</dependency>-->
		<dependency>
			<groupId>org.mule.runtime</groupId>
			<artifactId>mule-module-dsl-api</artifactId>
			<version>1.9.0</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-http-connector</artifactId>
			<version>1.10.3</version>
			<scope>provided</scope>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-jms-connector</artifactId>
			<version>1.9.7</version>
			<classifier>mule-plugin</classifier>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.17.0</version>
		</dependency>

		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>32.1.2-jre</version>
		</dependency>

		<dependency>
			<groupId>org.mule.sdk</groupId>
			<artifactId>mule-sdk-api</artifactId>
			<version>0.10.1</version>
		</dependency>

		<!--Logging -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>2.0.16</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
			<version>2.24.2</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>2.24.2</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-slf4j-impl</artifactId>
			<version>2.24.2</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-1.2-api</artifactId>
			<version>2.24.2</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>jcl-over-slf4j</artifactId>
			<version>2.0.16</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>jul-to-slf4j</artifactId>
			<version>2.0.16</version>
		</dependency>
	</dependencies>

</project>