module.name=advanced-logger

artifact.export.classPackages=au.com.apiled.module.api.component,\
        					  au.com.apiled.module.api.processor,\
        					  au.com.apiled.module.api.extension,\
        					  org.mule.runtime.core.internal.interception

artifact.export.resources= META-INF/mule.schemas,META-INF/advanced-logger-modules.xsd

artifact.privileged.classPackages=org.mule.runtime.core.privileged.interception,org.mule.runtime.core.internal.interception

artifact.privileged.artifactIds=